[common]
bind_addr = 0.0.0.0
bind_port = 4100

log_file = /tmp/frps.log

# set dashboard_addr and dashboard_port to view dashboard of frps
# dashboard_addr's default value is same with bind_addr
# dashboard is available only if dashboard_port is set
dashboard_addr = 0.0.0.0
dashboard_port = 4110

# dashboard user and passwd for basic auth protect
dashboard_user = admin
dashboard_pwd = Aa.123456